### ISSUE TITLE
Better Snippet Syntax name changed 

### ISSUE THREAD

**Issue by sarvex** [fox-land/vscode-hyperupcall-packs#2]
Better Snippet Syntax name changed to `https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-jsonc-syntax` but the location still refers to the old name `https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-snippet-syntax` which causes an 404 error

**Comment by hyperupcall** [comment]
Thanks! Fixed in 14813d9202dab39cbb99b07c77549b3cf2a8228a

**Comment by hyperupcall** [comment]
I just pushed the latest versions to Visual Studio Marketplace and the Open VSX Registry - they should be downloadable in a few minutes
